-- Shaman
QUICKHEAL_SPELL_LESSER_HEALING_WAVE = "Lesser Healing Wave";
QUICKHEAL_SPELL_HEALING_WAVE = "Healing Wave";

-- Priest
QUICKHEAL_SPELL_LESSER_HEAL = 'Lesser Heal';
QUICKHEAL_SPELL_HEAL = 'Heal';
QUICKHEAL_SPELL_GREATER_HEAL = 'Greater Heal';
QUICKHEAL_SPELL_FLASH_HEAL = 'Flash Heal';
QUICKHEAL_SPELL_RENEW = 'Renew';

-- Paladin
QUICKHEAL_SPELL_HOLY_LIGHT = 'Holy Light';
QUICKHEAL_SPELL_FLASH_OF_LIGHT = 'Flash of Light';

-- Druid
QUICKHEAL_SPELL_HEALING_TOUCH = 'Healing Touch';
QUICKHEAL_SPELL_REGROWTH = 'Regrowth';

FILTER_MT_PRIORITY_SHOW = 'MT Target Filter';

QH_STR_MT_PRIO_LIST = 'MT Priority';
QH_CLR_MT_PRIO = 'C';